
================================================================================
2024-10-26 22:17:12
Uncaught exception:
Traceback (most recent call last):
  File "C:\Users\gjust\Desktop\aloraBOT\alorabotlib\Cerberus.py", line 36, in <module>
    start()
  File "C:\Users\gjust\Desktop\aloraBOT\alorabotlib\Cerberus.py", line 33, in start
    preFight()
  File "C:\Users\gjust\Desktop\aloraBOT\alorabotlib\Cerberus.py", line 9, in preFight
    navigation.moveFromStallsAltarToStallsBank()
  File "C:\Users\gjust\Desktop\aloraBOT\alorabotlib\navigation.py", line 20, in moveFromStallsAltarToStallsBank
    actions.click(x, y, duration=[0.1, 1.1], sleepAfterClick=4, humanize=False)
  File "C:\Users\gjust\Desktop\aloraBOT\alorabotlib\actions.py", line 21, in click
    time.sleep(sleepAfterClick)
KeyboardInterrupt
================================================================================
