
================================================================================
2024-10-05 14:39:17
Uncaught exception:
Traceback (most recent call last):
  File "c:\Users\gjust\Desktop\aloraBOT\alorabotlib\bossing\test.py", line 3, in <module>
    actions.sd()
    ^^^^^^^^^^
AttributeError: module 'actions' has no attribute 'sd'
================================================================================
